### ISSUE TITLE
Logos svg et upload html5

### ISSUE THREAD

**Issue by mistergraphx** [cariagency/spip-logo-svg#1]
Hello, 

J'ai fais quelques tests du plugin, ça fonctionne bien, hormis quand j'utilise upload html5, ce qui est normal vu que upload html5 remplace le formulaire edier_logo ;-)

je me demandais si en utilisant les pipelines fomulaire_verifier, charger, traiter plutôt que la surcharge, il n'y aurait pas moyen de faire cohabiter les deux.

**Comment by julienmru** [comment]
Je ne suis pas sûr que ça résolve le problème, du coup je ne vais pas implémenter pour l'instant. Ceci dit, tu peux créer un fork et faire un pull request si tu arrives à tes fins :)

**Comment by mistergraphx** [comment]
En fait le plugin n'implemente pas les LOGO_DOCUMENT et c'est la partie qui me parait la plus importante dans l'utilisation, du svg au final. La après recherches ça demande a réécrire beaucoup de choses pour que la balise_LOGO_ prenne en compte ce que l'on veut.  Donc je vais plutot faire un plugin a part spip_document_svg ou spip_svg et necessité le tien pour le cas des logos d'objets éditoriaux.

Pour l'upload on verra plus tard, avec l'auteur du plugin upload_html5 ç'est plus de son ressort finalement.

Bonne journée et merci pour le plugin ;-)
