### ISSUE TITLE
Support du filtre balise_img

### ISSUE THREAD

**Issue by camlafit** [cariagency/spip-logo-svg#11]
Bonjour

Le filtre balise_img ne prend pas en charge par défaut le svg. Cela pourrait être bien de le surcharger :)

Merci

**Comment by mistergraphx** [comment]
En fait c'est toutes les fonctions d'image qu'il faut surcharger, et ce plugin ne s'occupe que des logos.
Du coup je ne pense pas que ce soit ici qu'il faille le faire, toutes les fonctions svg devrait en fait être dans un plugin (genre svgtools), puis intégré au core, ainsi que la lib qui nettoye, et ce plugin devrais ensuite utiliser, …

de mon avis ^^

**Comment by julienmru** [comment]
@camlafit Je n'ai pas forcément le besoin de cela, mais si tu surcharges les fonctions dans le plugin, tu pourras faire une pull-request pour incorporer les modifs au plugin :)
