### ISSUE TITLE
Mettre un if function_exists pour aide

### ISSUE THREAD

**Issue by y0hnn** [cariagency/spip-logo-svg#3]
Hello,

Sur SPIP 3.2 on a 
Fatal error: Uncaught Error: Call to undefined function aide() in /var/www/spip/plugins/logo-svg/formulaires/editer_logo.php:89

Il faudrait englober ceci d'un if (function_exists('aide'))

**Comment by kent1D** [comment]
Hello @yohannprigent je viens de forker le plugin pour changer quelques trucs : https://github.com/kent1D/spip-logo-svg

Avec celui là tu ne devrais pas avoir le problème du tout normalement

**Comment by julienmru** [comment]
@kent1D : pourrais-tu faire un pull-request que je regénère un paquet pour l'installation automatique ? Merci :)

**Comment by kent1D** [comment]
Je finis la sanitization là et je pull

**Comment by kent1D** [comment]
Ah merde tu as validé celle de tofulm qui n'est pas géniale, cf mon commentaire

**Comment by julienmru** [comment]
Pas de soucis, je revert et j'accepte ta PR.

**Comment by julienmru** [comment]
Voilà c'est mergé, je vais releaser la 1.2.0. Merci @kent1D :)

**Comment by y0hnn** [comment]
Trop cool @kent1D @julienmru je vais tester ça !

**Comment by kent1D** [comment]
Du coup si ça marche il faudrait changer la borne de compatibilité @julienmru
